<?php

function bdCrea(PDO $con)
{
 $con->exec(
  'CREATE TABLE IF NOT EXISTS
    USUARIO (
     USU_ID INTEGER,
     USU_NOMBRE TEXT NOT NULL,
     USU_APELLIDOP TEXT NOT NULL,
     USU_APELLIDOM TEXT NOT NULL,
     USU_CUE TEXT NOT NULL,
     USU_MATCH TEXT NOT NULL,
     CONSTRAINT USU_PK
      PRIMARY KEY(USU_ID),
     CONSTRAINT USU_CUE_UNQ
      UNIQUE(USU_CUE)
    )'
 );
 $con->exec(
  'CREATE TABLE IF NOT EXISTS
    ROL (
     ROL_ID TEXT NOT NULL,
     ROL_DESCRIPCION TEXT NOT NULL,
     CONSTRAINT ROL_PK
      PRIMARY KEY(ROL_ID),
     CONSTRAINT ROL_DESCR_UNQ
      UNIQUE(ROL_DESCRIPCION)
    )'
 );
 $con->exec(
  'CREATE TABLE IF NOT EXISTS
    USU_ROL (
     USU_ID INTEGER NOT NULL,
     ROL_ID TEXT NOT NULL,
     CONSTRAINT USU_ROL_PK
      PRIMARY KEY(USU_ID, ROL_ID),
     CONSTRAINT USU_ROL_USU_FK
      FOREIGN KEY (USU_ID)
      REFERENCES USUARIO(USU_ID),
     CONSTRAINT USU_ROL_ROL_FK
      FOREIGN KEY (ROL_ID)
      REFERENCES ROL(ROL_ID)
    )'
 );
 $con->exec(
   'CREATE TABLE IF NOT EXISTS
     OFICIOSv2(
       OFICIO_ID INTEGER NOT NULL,
       TIPO_OFICIO TEXT NOT NULL,
       DESCRIPCION_OFICIO TEXT NOT NULL,
       CONSTRAINT OFICIO_PKV1
        PRIMARY KEY(OFICIO_ID),
       CONSTRAINT OFICIO_TIPO_UNQ
        UNIQUE(TIPO_OFICIO)
     )'
 );
 $con->exec(
   'CREATE TABLE IF NOT EXISTS
     US_OFv2(
       ID_AB INTEGER NOT NULL,
       USER_ID_US INTEGER NOT NULL,
       OFICIOS_ID_OFICIO INTEGER NOT NULL,
       FECHA_ALTA DATE NOT NULL,
       CONSTRAINT US_OF_PKV1
        PRIMARY KEY(ID_AB, USER_ID_US, OFICIOS_ID_OFICIO),
       CONSTRAINT US_OFV2_USER_FK
        FOREIGN KEY (USER_ID_US)
        REFERENCES USUARIO(USU_ID),
       CONSTRAINT US_OFV2_OFICIOS_FK
        FOREIGN KEY (OFICIOS_ID_OFICIO)
        REFERENCES OFICIOSv2(OFICIO_ID)
     )
   '
 );
}
