<?php

function bdCrea(PDO $con)
{
    $con->exec(
        'CREATE TABLE IF NOT EXISTS ARCHIVO (
           ARCH_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
           ARCH_BYTES BLOB NOT NULL
        )'
    );

    $con->exec(
        'CREATE TABLE IF NOT EXISTS USUARIO (
           USU_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
           USU_NOMBRE VARCHAR(255) NOT NULL,
           USU_APELLIDOP VARCHAR(255) NOT NULL,
           USU_APELLIDOM VARCHAR(255) NOT NULL,
           USU_CUE VARCHAR(225) NOT NULL UNIQUE,
           USU_MATCH VARCHAR(255) NOT NULL,
           USU_FECHA_NAC DATE NOT NULL,
           USU_LUGAR_NAC TEXT,
           USU_CURP TEXT,
           USU_FOTOGRAFIA INTEGER,
           USU_TELEFONO VARCHAR(12),
           USU_UBICACION TEXT,
           USU_COMP_DOM_DOC TEXT,
           USU_DIRECCION TEXT,
           CONSTRAINT USU_ARCH_FK FOREIGN KEY(USU_FOTOGRAFIA) REFERENCES ARCHIVO(ARCH_ID)
      )'
  );

  $con->exec(
      'CREATE TABLE IF NOT EXISTS ROL (
          ROL_ID VARCHAR(225) PRIMARY KEY,
          ROL_DESCRIPCION VARCHAR(225) NOT NULL UNIQUE
      )'
  );


    $con->exec(
        'CREATE TABLE IF NOT EXISTS USU_ROL (
         USU_ID INTEGER NOT NULL,
         ROL_ID VARCHAR(225) NOT NULL,
         PRIMARY KEY(USU_ID, ROL_ID),
         CONSTRAINT USU_ROL_USU_FK FOREIGN KEY (USU_ID) REFERENCES USUARIO(USU_ID),
         CONSTRAINT USU_ROL_ROL_FK FOREIGN KEY (ROL_ID) REFERENCES ROL(ROL_ID)
        )'
    );

  $con->exec(
      'CREATE TABLE IF NOT EXISTS OFICIOSv2 (
         OFICIO_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
         TIPO_OFICIO VARCHAR(225) NOT NULL UNIQUE,
         DESCRIPCION_OFICIO TEXT NOT NULL
      )'
  );

    $con->exec(
        'CREATE TABLE IF NOT EXISTS US_OFv2 (
           ID_AB INTEGER PRIMARY KEY AUTO_INCREMENT,
           USER_ID_US INTEGER NOT NULL,
           OFICIOS_ID_OFICIO INTEGER NOT NULL,
           FECHA_ALTA DATE NOT NULL,
           CONSTRAINT US_OFV2_USER_FK FOREIGN KEY (USER_ID_US) REFERENCES USUARIO(USU_ID),
           CONSTRAINT US_OFV2_OFICIOS_FK FOREIGN KEY (OFICIOS_ID_OFICIO) REFERENCES OFICIOSv2(OFICIO_ID)
         )'
    );

    $con->exec(
         'CREATE TABLE IF NOT EXISTS SERV (
            ID_SERVICIO INTEGER PRIMARY KEY AUTO_INCREMENT,
            TIPO_SERVICIO VARCHAR(225) NOT NULL UNIQUE,
            DESCRIPCION_DE_SERVICIO TEXT NOT NULL,
            SERV_OFICIOS_ID_OFICIOS INTEGER NOT NULL,
            CONSTRAINT SERV_OFICIOS_FK FOREIGN KEY (SERV_OFICIOS_ID_OFICIOS) REFERENCES OFICIOSv2(OFICIO_ID)
         )'
    );

}
